In [7]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer
from sklearn import preprocessing
from sklearn.decomposition import PCA

In [8]:
df= pd.read_csv("D:/Kuliah/Semester 3/UAS datmin/indek IPM PMI.csv")
df.head(5)

,tahun,pct_tdk_cukup_pangan,prov,persen_anak_dengan_akte_lahir,kepadatan_penduduk,persen_penduduk_trampil_tik,proporsi_hidup_dibawah_50_persen_median_pendapatan
0,2021,6.90,ACEH,94.52,92,60.21,9.98
1,2021,6.33,SUMATERA UTARA,83.02,205,67.41,5.87
2,2021,6.02,SUMATERA BARAT,91.38,133,68.00,2.47
3,2021,10.61,RIAU,84.25,75,70.69,2.52
4,2021,9.25,JAMBI,93.37,72,64.47,5.91

In [9]:
#Hapus colom provinsi
df.drop("prov",axis=1)

,tahun,pct_tdk_cukup_pangan,persen_anak_dengan_akte_lahir,kepadatan_penduduk,persen_penduduk_trampil_tik,proporsi_hidup_dibawah_50_persen_median_pendapatan
0,2021,6.90,94.52,92,60.21,9.98
1,2021,6.33,83.02,205,67.41,5.87
2,2021,6.02,91.38,133,68.00,2.47
3,2021,10.61,84.25,75,70.69,2.52
4,2021,9.25,93.37,72,64.47,5.91
...,...,...,...,...,...,...
100,2019,34.12,78.66,38,44.02,10.75
101,2019,35.81,79.20,39,38.11,6.60
102,2019,19.22,75.05,9,52.37,11.28
103,2019,38.21,45.88,11,26.45,17.80
104,2019,7.63,86.01,140,58.22,11.93

In [20]:
df['persen_anak_dengan_akte_lahir'] = df['persen_anak_dengan_akte_lahir'].astype('string')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   tahun                                               105 non-null    int64
 1   pct_tdk_cukup_pangan                                105 non-null    object
 2   prov                                                105 non-null    object
 3   persen_anak_dengan_akte_lahir                       105 non-null    string
 4   kepadatan_penduduk                                  105 non-null    int64
 5   persen_penduduk_trampil_tik                         105 non-null    float64
 6   proporsi_hidup_dibawah_50_persen_median_pendapatan  105 non-null    float64
dtypes: float64(2), int64(2), object(2), string(1)
memory usage: 5.9+ KB

In [14]:
df.loc[(df['pct_tdk_cukup_pangan'] < 60), 'pct_tdk_cukup_pangan'] = "Sangat Rendah"

TypeError: '<' not supported between instances of 'str' and 'int'

In [15]:
df.head(50)

,tahun,pct_tdk_cukup_pangan,prov,persen_anak_dengan_akte_lahir,kepadatan_penduduk,persen_penduduk_trampil_tik,proporsi_hidup_dibawah_50_persen_median_pendapatan
0,2021,Sangat Rendah,ACEH,94.52,92,60.21,9.98
1,2021,Sangat Rendah,SUMATERA UTARA,83.02,205,67.41,5.87
2,2021,Sangat Rendah,SUMATERA BARAT,91.38,133,68.00,2.47
3,2021,Sangat Rendah,RIAU,84.25,75,70.69,2.52
4,2021,Sangat Rendah,JAMBI,93.37,72,64.47,5.91
5,2021,Sangat Rendah,SUMATERA SELATAN,90.05,93,62.59,13.24
6,2021,Sangat Rendah,BENGKULU,94.52,102,62.10,8.37
7,2021,Sangat Rendah,LAMPUNG,93.51,262,65.76,12.12
8,2021,Sangat Rendah,KEP. BANGKA BELITUNG,96.05,90,66.33,0.01
9,2021,Sangat Rendah,KEP. RIAU,94.20,258,89.06,1.59
10,2021,Sangat Rendah,DKI JAKARTA,96.93,15978,91.79,0.18
11,2021,Sangat Rendah,JAWA BARAT,84.76,1379,76.08,11.50
12,2021,Sangat Rendah,JAWA TENGAH,96.03,1120,71.15,18.41
13,2021,Sangat Rendah,DI YOGYAKARTA,98.14,1185,84.72,12.94
14,2021,Sangat Rendah,JAWA TIMUR,91.00,855,68.07,15.56
15,2021,Sangat Rendah,BANTEN,84.56,1248,75.69,4.20
16,2021,Sangat Rendah,BALI,93.28,755,77.09,5.74
17,2021,Sangat Rendah,NUSA TENGGARA BARAT,88.70,290,58.69,16.30
18,2021,Sangat Rendah,NUSA TENGGARA TIMUR,65.66,111,53.16,29.00
19,2021,Sangat Rendah,KALIMANTAN BARAT,90.01,37,62.04,6.53
20,2021,Sangat Rendah,KALIMANTAN TENGAH,86.96,18,66.43,3.40
21,2021,Sangat Rendah,KALIMANTAN SELATAN,91.49,106,70.39,3.24
22,2021,Sangat Rendah,KALIMANTAN TIMUR,93.16,30,81.17,1.13
23,2021,Sangat Rendah,KALIMANTAN UTARA,92.96,9,76.94,0.31
24,2021,Sangat Rendah,SULAWESI UTARA,90.15,190,69.77,12.43
25,2021,Sangat Rendah,SULAWESI TENGAH,85.11,49,58.19,11.39
26,2021,Sangat Rendah,SULAWESI SELATAN,91.47,196,67.29,19.05
27,2021,Sangat Rendah,SULAWESI TENGGARA,90.58,70,65.75,21.73
28,2021,Sangat Rendah,GORONTALO,94.02,105,61.94,20.84
29,2021,Sangat Rendah,SULAWESI BARAT,91.83,86,55.72,25.74
30,2021,Sangat Rendah,MALUKU,81.63,40,59.26,7.73
31,2021,Sangat Rendah,MALUKU UTARA,84.42,41,51.53,6.34
32,2021,Sangat Rendah,PAPUA BARAT,74.74,11,62.31,10.84
33,2021,Sangat Rendah,PAPUA,45.19,14,30.58,13.35
34,2021,Sangat Rendah,INDONESIA,88.42,142,70.17,11.61
35,2020,Sangat Rendah,ACEH,93.84,91,54.25,9.53
36,2020,Sangat Rendah,SUMATERA UTARA,80.45,203,58.60,6.32
37,2020,Sangat Rendah,SUMATERA BARAT,90.10,132,58.67,2.49
38,2020,Sangat Rendah,RIAU,81.83,73,62.67,3.26
39,2020,Sangat Rendah,JAMBI,93.73,71,56.87,6.21
40,2020,Sangat Rendah,SUMATERA SELATAN,90.65,92,54.52,14.31
41,2020,Sangat Rendah,BENGKULU,92.77,101,53.42,8.23
42,2020,Sangat Rendah,LAMPUNG,91.65,260,55.57,13.04
43,2020,Sangat Rendah,KEP. BANGKA BELITUNG,96.07,89,60.37,0.16
44,2020,Sangat Rendah,KEP. RIAU,94.71,252,81.73,1.84
45,2020,Sangat Rendah,DKI JAKARTA,97.52,15907,88.08,0.07
46,2020,Sangat Rendah,JAWA BARAT,85.72,1365,71.09,11.42
47,2020,Sangat Rendah,JAWA TENGAH,96.26,1113,65.78,18.50
48,2020,Sangat Rendah,DI YOGYAKARTA,98.36,1171,81.36,12.54
49,2020,Sangat Rendah,JAWA TIMUR,91.62,851,63.91,16.08

In [17]:
df.loc[(df['persen_anak_dengan_akte_lahir'] < 60), 'persen_anak_dengan_akte_lahir'] = "Sangat Rendah"
df.loc[(60 < df['persen_anak_dengan_akte_lahir'] < 70 ), 'persen_anak_dengan_akte_lahir'] = "Sedang"
df.loc[(70 < df['persen_anak_dengan_akte_lahir'] < 80 ), 'persen_anak_dengan_akte_lahir'] = "Tinggi"
df.loc[(80 < df['persen_anak_dengan_akte_lahir'] ), 'persen_anak_dengan_akte_lahir'] = "Sangat Tinggi"

TypeError: '<' not supported between instances of 'str' and 'int'